### ISSUE TITLE
Confirm promise is not rejected on backdrop click or escape key down

### ISSUE THREAD

**Issue by andrii-pavlykivskyi** [jonatanklosko/material-ui-confirm#104]
I want to control state of dialog to know if it's opened or not.
I've provided prop to change state on dialog closed but it doesn't seem to be invoked
```ts
setOpen(true);
          confirm({
            dialogProps: {
              onClose: () => {
                setOpen(false);
              },
            },
            ...
          })
```

**Comment by jonatanklosko** [comment]
The `onClose` dialog callback is controlled by this library, so passing it in the props is ignored. You need to use then/catch to wait for the promise to be resolved, but since it is not resolved for natural close (backdrop click and escape), you'd need to use `allowClose: false` for that to work reliably.

**Comment by MichaelDimmitt** [comment]
Going to put together a quick pr later tonight with some of these ideas.
maybe a boolean prop named rejectNaturalClose ?
See also: https://github.com/jonatanklosko/material-ui-confirm/issues/41#issuecomment-2635133764

**Comment by jonatanklosko** [comment]
@MichaelDimmitt I've just published v4 with a new Promise API. See [the changelog](https://github.com/jonatanklosko/material-ui-confirm/blob/master/CHANGELOG.md#400) for more information.
