### ISSUE TITLE
How to use this as class component

### ISSUE THREAD

**Issue by govindtotla** [jonatanklosko/material-ui-confirm#13]
useConfirm() is a react hook and cant be used in class component either we have to change class component to functional componant but that will be lengthy. What is the other way to useConfirm as Class component? It is not working on Render() also. I am new to React.

**Comment by CycoPH** [comment]
Here is some code:
There is a Component that uses the <HistoryDialog> to show a button. When you press the button it will ask you a question.  With a positive reply the doAction is called
---
import React from 'react';
import HistoryDialog from './HistoryDialog';

class MonitorPageContainer extends React.Component {

	doAction = () => {
		console.log("You confirmed something);
	}
	render() {
		return (
			<>
				<HistoryDialog doAction={this.doAction} />
			</>
		)
	}
}

So that would be React.Component base.

Here is my HistoryDialog.js:
import React, { useState, useEffect } from 'react';
import { useConfirm } from 'material-ui-confirm';
const HistoryDialog = ({doAction}) => {
    const askSomething = async () => {
		try {
			await confirm( {
				description: `Are you sure you want to do that?`,
				confirmationText: "Yes switch state",
			});
			doAction();
		}
		catch(ex) {
		}
	}

	return (
		<Button variant="contained" onClick={askSomething }>Click to confirm</Button>
	)
}
export default HistoryDialog;

**Comment by jonatanklosko** [comment]
Hey, initially this package exposed a HOC and supported classes, but I moved to a more modern and simpler to use API and it does support functional components only.

> either we have to change class component to functional component but that will be lengthy

How is a functional component lengthy as compared to the class alternative? It's usually the other way round ^^

Anyway, if you prefer HOC you can still create one. See a sample `withConfirm` [in this demo](https://codesandbox.io/s/material-ui-confirm-demo-rzj0p?file=/src/Demo.js).
