### ISSUE TITLE
[FEAT] Embed forms in confirm dialog

### ISSUE THREAD

**Issue by jsakas** [jonatanklosko/material-ui-confirm#21]
It would be amazing if this library supported embedding form inputs and other layout elements for purposes such as:

- typing the name of a resource before deletion
- entering a password to confirm account change

**Comment by unrealcloud** [comment]
Hey guys! Since this PR https://github.com/jonatanklosko/material-ui-confirm/issues/14, I'm able to embed forms this way:

```
        confirm({
            title: 'Reauthenticate',
            description: <LoginForm onLogin={() => setShowLoginModal(false)} />,     <-- MY FORM IS HERE
            dialogProps: {
              open: showLoginModal,                         <-- CONTROLLED DIALOG
            },
            confirmationButtonProps: {
              style: {
                display: 'none',                     <-- HIDDEN CONFIRMATION BUTTON SINCE MY FORM ALREADY HAS ITS BUTTON
              },
            },
            cancellationButtonProps: {
              fullWidth: true,
              variant: 'contained',
            },
          })
```

It's all working perfectly, as you can see in this screenshot:

<img width="638" alt="Screen Shot 2021-02-16 at 11 10 39 PM" src="https://user-images.githubusercontent.com/70619669/108155233-8308a600-70ac-11eb-8c11-98cf97bff33d.png">

EXCEPT for those errors:

<img width="705" alt="Screen Shot 2021-02-16 at 11 14 25 PM" src="https://user-images.githubusercontent.com/70619669/108155351-bb0fe900-70ac-11eb-89e9-d28dd8691095.png">

Since Material UI's [`<DialogContentText />`](https://material-ui.com/api/dialog-content-text/) passes all its props to the underlying `Typography` component, it means we can use it as

```
<DialogContentText component="div">
    // now we can put ANYTHING here :)
</DialogContentText>
```

Thoughts?

**Comment by jonatanklosko** [comment]
> EDIT: Actually passing the open prop to dialogProps doesn't allow me to control the Confirmation dialog's state! :( If it could, it'd be easy to render forms in the modal as above.

Yeah, the dialog is already controlled by this package. Forms seems like a case that needs more customization, perhaps [this comment](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227) will help.

**Comment by jonatanklosko** [comment]
This is out of the scope of this package, as it means to maximally encapsulate the dialog markup. For more complex use cases I suggest an alternative approach outlined [here](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227).
