### ISSUE TITLE
Feature request: cancel without rejecting Promise

### ISSUE THREAD

**Issue by ondrejpar** [jonatanklosko/material-ui-confirm#61]
Hi, thanks for the great library.
It would be nice to have an option to not reject the promise on cancel, as cancellation is often a no-op and we could get rid of the confusing catch.
I think it would be sufficient to just store () => {} as "reject" value in resolveReject state.

**Comment by jonatanklosko** [comment]
Hey @ondrejpar! This is intentional, it allows to distinguish between explicit cancel and natural close like Escape or backdrop click (in which case the promise neither resolves nor rejects). If you want a different behaviour you can create a simple wrapper with the desired behaviour, for example https://github.com/jonatanklosko/material-ui-confirm/issues/41#issuecomment-980782976 shows how to resolve with a boolean instead of rejecting :)
